[package]
name = "jupyter-shell"
version = "0.1.0"
authors = ["YuviPanda <yuvipanda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
websocket = "0.26"
hyper = "0.10"
